### ISSUE TITLE
Wrongly linked step definitions with cucumber expressions

### ISSUE THREAD

**Issue by Tammo0987** [vbmacher/intellij-cucumber-scala#122] opened 2023-11-10 21:02 UTC
**Describe the bug**
When I create a step definition with a cucumber expression instead of a regex, then the plugin will also link the step, when there is any additional characters before or/and after it. But when I execute it, cucumber won't find the step. 

**Expected behavior**
The plugin will only link the step, if it exactly matches the cucumber expression. If it has any additional pre- or suffix, it won't be linked.

**Example**
Here is an example:

```scala
Given("basic step with string {string}") { (value: String) => ??? }
```

```gherkin
# Links as expected
Given basic step with string "a"

# Links, but unexpected
And basic step with string "a" suffix
```

**Comment by vbmacher** [comment] 2023-11-11 13:09
Thanks @Tammo0987 I'll look into it

**Comment by vbmacher** [comment] 2023-11-14 09:27
The issue is now fixed, and the plugin is released with the fix

**Closed by vbmacher** 2023-11-14 09:27 UTC

**Comment by Tammo0987** [comment] 2023-11-16 09:42
Thank you for your fast work, does work as expected now 😄
